services:
    # SQL server for structured data
    psql:
        image: timescale/timescaledb:latest-pg13
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/psql_password
    
    # NoSQL server for unstructured data
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_password

    # Redis as a cache
    redis:
        image: redis:latest

secrets:
    psql_password:
        file: ./secrets/psql_password
    mongo_password:
        file: ./secrets/mongo_password
